/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b84317f1-1110-4a02-80d0-e09c5e1fd0b4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_vqZtBenI7",
    "aws_user_pools_web_client_id": "4c6f1bg8iluhadg8kvi3a0v2db",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "charger",
            "endpoint": "https://e9qzn3xqgc.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "documentdata132943-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
